import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Panel } from "./components/Panel/Panel";
import Image from "next/image";
import CalendarPanel from "./components/Calendar/CalendarPanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CalPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
